config/routes.rb
Fightscore::Application.routes.draw do
  devise_for :users

  root :to => "fights#index"
  
  resources :fights do
    member do
      get 'score'
      get 'new_fight_rounds'
      get 'create_all_rounds'
      get 'destroy_all_scores'
    end
  end
  resources :fighters
  resources :rounds
  resources :scores
  
  #match '/fight/:id/score', :controller => 'scores', :action => 'create_scores'
  
end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  attr_accessible :fight_id, :round_id, :name
  has_many :rounds
  has_many :fights, :through => :rounds, :uniq => true
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  # GET /fighters
  # GET /fighters.json
  def index
    @fighters = Fighter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fighters }
    end
  end

  # GET /fighters/1
  # GET /fighters/1.json
  def show
    @fighter = Fighter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fighter }
    end
  end

  # GET /fighters/new
  # GET /fighters/new.json
  def new
    @fighter = Fighter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fighter }
    end
  end

  # GET /fighters/1/edit
  def edit
    @fighter = Fighter.find(params[:id])
  end

  # POST /fighters
  # POST /fighters.json
  def create
    @fighter = Fighter.new(params[:fighter])

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.json { render json: @fighter, status: :created, location: @fighter }
      else
        format.html { render action: "new" }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fighters/1
  # PUT /fighters/1.json
  def update
    @fighter = Fighter.find(params[:id])

    respond_to do |format|
      if @fighter.update_attributes(params[:fighter])
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  # DELETE /fighters/1.json
  def destroy
    @fighter = Fighter.find(params[:id])
    @fighter.destroy

    respond_to do |format|
      format.html { redirect_to fighters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fighters_helper.rb
module FightersHelper
  def find_fights_fighters(fight_id)
    fight = Fight.find(fight_id)
    fighters = fight.fighters
    return fighters
  end
end

app/views/fighters/_form.html.erb
<%= form_for(@fighter) do |f| %>
  <% if @fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
      <% @fighter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
	  <%= f.text_field :name %>
	<%= f.submit %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing fighter</h1>

<%= render 'form' %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<h1>Listing fighters</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fighters.each do |fighter| %>
  <tr>
	<td><%= fighter.name %> </td>
	<td><%= link_to 'Show', fighter %></td>
    <td><%= link_to 'Edit', edit_fighter_path(fighter) %></td>
    <td><%= link_to 'Destroy', fighter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fighter', new_fighter_path %>

app/views/fighters/new.html.erb
<h1>New fighter</h1>

<%= render 'form' %>

<%= link_to 'Back', fighters_path %>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>