config/routes.rb
Fightscore::Application.routes.draw do
  devise_for :users

  root :to => "fights#index"
  
  resources :fights do
    member do
      get 'score'
      get 'new_fight_rounds'
      get 'create_all_rounds'
      get 'destroy_all_scores'
    end
  end
  resources :fighters
  resources :rounds
  resources :scores
  
  #match '/fight/:id/score', :controller => 'scores', :action => 'create_scores'
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :score, :round_id, :user_id
  
  belongs_to :round
  belongs_to :user
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  
  def find_fight(score)
    round = Round.find(score.round_id)
    fight = Fight.find(round.fight_id)
  end
  
  def index
    @scores = Score.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])
    @fight = find_fight(@score)

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @fight, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
	Score: <%= f.number_field :score %>
	Round ID: <%= f.number_field :round_id %>
	User ID: <%= f.number_field :user_id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>