config/routes.rb
Fightscore::Application.routes.draw do
  devise_for :users

  root :to => "fights#index"
  
  resources :fights do
    member do
      get 'score'
      get 'new_fight_rounds'
      get 'create_all_rounds'
      get 'destroy_all_scores'
    end
  end
  resources :fighters
  resources :rounds
  resources :scores
  
  #match '/fight/:id/score', :controller => 'scores', :action => 'create_scores'
  
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :roundname, :fight_id, :fighter_id
  belongs_to :fighter
  belongs_to :fight
  has_many :scores
  # has_many :users, :through => :scores
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  # GET /rounds
  # GET /rounds.json
  
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    #@fight = Fight.find(params[:fight_id])
    @fights = Fight.all
    @rounds = Round.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @user = current_user
    @round = Round.find(params[:id])
    @fighter = Fighter.find(@round.fighter_id)
    @score = Score.find_by_user_id(@user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(params[:round])

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render json: @round, status: :created, location: @round }
      else
        format.html { render action: "new" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id])
    @fight = Fight.find(@round.fight_id)

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to @fight, notice: 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  ##
  #def create_rounds(num_of_rounds, fightid, fighterid)
  #  i = 1
  #  num_of_rounds.times do
  #    Round.create(fight_id: fightid, fighter_id: fighterid, roundname: i)
  #    i++
  #  end
  #end
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  Fight ID: <%= f.number_field :fight_id %>
  Round: <%= f.number_field :roundname %>
  Fighter ID: <%= f.number_field :fighter_id %>
  
  <div class="actions">
   	<%= f.submit %>
  </div>
  
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Listing rounds</h1>

<ul>
<% @fights.each do |fight| %>
	<li><%= fight.date %> (ID: <%= fight.id %>)</li>
	<ul>
		<% fighters = find_fights_fighters(fight.id) %>
		<% fighters.uniq.each do |fighter| %>
			<li><%= fighter.name %> (ID: <%= fighter.id %>)</li>
			<ul>
				<% rounds = find_rounds_for_fights_fighter(fight.id, fighter.id) %>
				<% rounds.each do |round| %>
					<li>Round #<%= round.roundname %> (ID: <%= round.id %>)</li>
				<% end %>
			</ul>
		<% end %>
	</ul>
<% end %>
</ul>
  
<table>
<% @rounds.each do |round| %>
  <tr>
	<td><%= round.id %></td>
	<td><%= round.roundname %></td>
	<td><%= link_to 'Show', round_path(round) %></td>
    <td><%= link_to 'Edit', edit_round_path(round) %></td>
    <td><%= link_to 'Destroy', round_path(round), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Create Rounds', new_round_path %>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>
<%= @fighter.name %>
<%= @round.fight.date %>
<br/>
Fighters:
<% @round.fight.fighters.uniq.each do |fighter| %>
	<%= fighter.name %>
<% end %>
<!-- <br/>
Score: <%= @score.score %>
<br/>
<%= form_for @score do |f| %>
	<%= f.number_field :score %>
	<%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_round_path(@round) %>  -->