config/routes.rb
Fightscore::Application.routes.draw do
  devise_for :users

  root :to => "fights#index"
  
  resources :fights do
    member do
      get 'score'
      get 'new_fight_rounds'
      get 'create_all_rounds'
      get 'destroy_all_scores'
    end
  end
  resources :fighters
  resources :rounds
  resources :scores
  
  #match '/fight/:id/score', :controller => 'scores', :action => 'create_scores'
  
end

app/models/fight.rb
class Fight < ActiveRecord::Base
  attr_accessible :date, :numrounds
  has_many :rounds
  has_many :fighters, :through => :rounds
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  # GET /fights
  # GET /fights.json
  before_filter :find_current_user
  before_filter :authenticate_user!, :except => :index
  
  def find_current_user
    @user = current_user
  end
  
  def index
    @fights = Fight.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fights }
    end
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
    @fight = Fight.find(params[:id])
    # @eligible_scores = 0
    # @rounds = Round.find_all_by_fight_id(@fight.id)
#     i = 0
#     @rounds.each do |round|
#       Score.find_by_round_id(round.id)
#     end
      
                  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fight }
    end
  end

  # GET /fights/new
  # GET /fights/new.json
  def new
    @fight = Fight.new
    @fighters = Fighter.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fight }
    end
  end

  # GET /fights/1/edit
  def edit
    @fight = Fight.find(params[:id])
  end

  # POST /fights
  # POST /fights.json
  def create
    @fight = Fight.new(params[:fight])

    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render json: @fight, status: :created, location: @fight }
      else
        format.html { render action: "new" }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fights/1
  # PUT /fights/1.json
  def update
    @fight = Fight.find(params[:id])

    respond_to do |format|
      if @fight.update_attributes(params[:fight])
        format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fights/1
  # DELETE /fights/1.json
  def destroy
    @fight = Fight.find(params[:id])
    @fight.destroy

    respond_to do |format|
      format.html { redirect_to fights_url }
      format.json { head :no_content }
    end
  end
  
  def score
    @fight = Fight.find(params[:id])
    @rounds = Round.find_all_by_fight_id(@fight.id)
  
      @rounds.each do |round|
        if Score.exists?(:round_id => round.id, :user_id => @user.id) # checks to make sure that this record doesn't exist already so it does not overwrite existing scores
        else
          Score.create(round_id: round.id, user_id: @user.id)
        end
      end
    redirect_to @fight
  end
  
  def new_fight_rounds
    @fight = Fight.find(params[:id]) #we can figure out the fight_id this way and we can do @fight.fighters to find the fighter IDs
    @round = Round.new
  end
  
  def create_all_rounds
    fight = Fight.find(params[:id])
    fighters = fight.fighters
    
    fighters.uniq.each do |fighter|
      #checks to make sure that there are not rounds created yet
      fighter_rounds = Round.find_all_by_fight_id_and_fighter_id(fight.id,fighter.id).count 
      if fighter_rounds != fight.numrounds
        i = 2
        while i < fight.numrounds+1 do
          Round.create(fight_id: fight.id, fighter_id: fighter.id, roundname: i)
          i += 1
        end
      end
    end
    redirect_to fight, notice: 'Already has appropriate # of rounds created'
  end
  
  def destroy_all_scores
    @fight = Fight.find(params[:id])
    @rounds = Round.find_all_by_fight_id(@fight.id)
    
    @rounds.each do |round|
      Score.find_by_round_id_and_user_id(round.id, @user.id).destroy
    end
    
    score
  end
end

app/helpers/fights_helper.rb
module FightsHelper
  def find_rounds_for_fights_fighter(fight_id, fighter_id)
    rounds = Round.find_all_by_fight_id_and_fighter_id(fight_id, fighter_id)
    return rounds
  end
  
  def find_users_score_for_round(round_id, user_id)
    score = Score.find_by_round_id_and_user_id(round_id, user_id)
    return score
  end
  
  def find_fights_fighters(fight_id)
    fight = Fight.find(fight_id)
    fighters = fight.fighters
    return fighters
  end
  
  def find_all_fighters
    fighters = Fighter.all
    return fighters
  end
  
  def find_all_rounds_for_fight(fight_id)
    rounds = Round.find_all_by_fight_id(fight_id)
    return rounds
  end
  
  def calculate_total_score(fight_id, fighter_id, user_id)
    @fight = Fight.find(fight_id)
    @rounds = Round.find_all_by_fight_id_and_fighter_id(@fight.id, fighter_id)
    fighter_score = 0
    
    @rounds.each do |round|
      fighter_score = fighter_score + Score.find_by_round_id_and_user_id(round.id, user_id).score
    end
    
    fighter_score
  end
  
  def find_all_users_scores_for_round(round_id)
    scores = Score.find_all_by_round_id(round_id)
    return scores
  end
  
  # def avg_score(scores)
#     avg_score = (score / scores.count)
#     return avg_score
#   end
  
  # def calculate_all_users_score(fight_id, fighter_id)
#     @fight = Fight.find(fight_id)
#     @rounds = Round.find_all_by_fight_id_and_fighter_id(@fight.id, fighter_id)
    
end

app/views/fights/_choose_fighters.html.erb
<% @fighters = find_all_fighters %>

<% @fighters.each do |fighter| %>
	<%= fighter.name %>
<% end %>

app/views/fights/_form.html.erb
<%= form_for(@fight) do |f| %>
  <% if @fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
      <% @fight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
	Date: <%= date_select :fight, :date, :start_year => 1950 %>
	<br/>
	Number of Rounds: <%= f.number_field :numrounds %>
	<br/>
	<%= f.submit %>
  </div>
<% end %>

app/views/fights/_score_form.html.erb
<%= form_for @score do |f| %>
	<%= f.number_field :score, options = { :min => 6, :max => 10, :class => "input-mini" } %>
	<%= f.submit "Score" %>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing fight</h1>

<strong>Fighters</strong>
<br/>
<ul>
	<% @fight.fighters.uniq.each do |fighter| %>
		<li><%= fighter.name %></li>
	<% end %>
</ul>

<strong>Rounds</strong>
<br/>
<ul>
	<% @fight.rounds.each do |round| %>
		<li><%= round.roundname %></li>
	<% end %>
</ul>



<%#= render 'create_rounds' %>
<%= render 'choose_fighters' %>


<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>

app/views/fights/index.html.erb
<h1>Fights</h1>
<div align="center">
	CallTheFight.com is an easy way for you to score fights as you watch them.  
	<br/>
	During and after the fight, we show you the scores from all CallTheFight.com fight fans tallied up to determine the fight's winner.
	<br/>
	Join in on the fun and call the next big fight!
</div>
<div class="container">
	<h3>Score Upcoming Fights</h3>
	<% @fights.each do |fight| %>
			<% if fight.date >= Date.today %>
				<div class="span2" align="center">
					<% i = 0 %>
					<%= fight.date %>
					<br/>
					<% fight.fighters.uniq.each do |fighter| %>
						<% i += 1%>
						<strong><%= fighter.name %></strong>
						<% if i < 2 %> 
						<br/>vs.</br>
						<% end %>
					<% end %>
					<br/>
					<%= fight.numrounds %> round fight.
					<br/>
					<%= link_to 'Score this Fight', score_fight_path(fight) %>
					<%#= link_to 'Show scores', fight_path(fight) %>
				    <%#= link_to 'Edit', edit_fight_path(fight) %>
				    <%#= link_to 'Destroy', fight, method: :delete, data: { confirm: 'Are you sure?' } %>
					<%#= link_to 'Create Rounds', create_rounds_fight_path(fight) %>
					<%#= link_to 'Create Fight Rounds', create_all_rounds_fight_path(fight) %>
				</div>
			<% end %>
	<% end %>
</div>
<div class="container">
	<h3>Score Past Fights</h3>
	<% @fights.each do |fight| %>
			<% if fight.date < Date.today %>
				<div class="span2" align="center">
					<% i = 0 %>
					<%= fight.date %>
					<br/>
					<% fight.fighters.uniq.each do |fighter| %>
						<% i += 1%>
						<strong><%= fighter.name %></strong>
						<% if i < 2 %> 
						<br/>vs.</br>
						<% end %>
					<% end %>
					<br/>
					<%= fight.numrounds %> round fight.
					<br/>
					<%= link_to 'Score this Fight', score_fight_path(fight) %>
					<%#= link_to 'Show scores', fight_path(fight) %>
				    <%#= link_to 'Edit', edit_fight_path(fight) %>
				    <%#= link_to 'Destroy', fight, method: :delete, data: { confirm: 'Are you sure?' } %>
					<%#= link_to 'Create Rounds', create_rounds_fight_path(fight) %>
					<%#= link_to 'Create Fight Rounds', create_all_rounds_fight_path(fight) %>
				</div>
			<% end %>
	<% end %>
</div>
<div class="container">
	<div class="span12">
		<iframe src="https://docs.google.com/forms/d/1XjsJv1RtB9tU9w9WEizHsMNZlLrvBMaj6To7Wn9lomY/viewform?embedded=true" width="760" height="200" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
	</div>
</div>
<div class="container">
	<div class="span12">
		<%= image_tag "screenshot.png", :size => "877x526" %>
	</div>
</div>

<%#= link_to 'New Fight', new_fight_path %>

app/views/fights/new.html.erb
<h1>New fight</h1>

<%= render 'form' %>

<%= link_to 'Back', fights_path %>

app/views/fights/new_fight_rounds.html.erb
<br/>
This is for fight # <%= @fight.id %>
<br/>
These are the fighter IDs:
<br/>
<% @fight.fighters.uniq.each do |fighter| %>
	<%= fighter.id %><br/>
<% end %>
<br/>
This is the # of rounds for this fight:
<br/>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>
<% fighters = find_fights_fighters(@fight.id) %>
<% i = 0 %>
<div class="container">
	<div class="row">
		<div class="span20">
			<h1>
			<% fighters.uniq.each do |fighter| %>
				<% i = i + 1 %>
				<%= fighter.name %>
				<% if i < 2 %> 
				vs.
				<% end %>
			<% end %>
			</h1>
			</div>
	</div>
</div>
<div class="container">
	<strong>Instructions:</strong> Score for each round for each fighter.  Hit the "Score" button for each fighter's round to save the score before entering scores for other rounds.  The total score will update as you save your scores.
</div>
<div class="container">
	<h4>Your Scorecard</h4>
	<%= render 'round_table' %>
	<% fighters.uniq.each do |fighter| %>
	<div class="row">
		<div class="span1"><%= fighter.name %></div>
			<% fighters_rounds = find_rounds_for_fights_fighter(@fight.id, fighter.id) %>
			<% fighters_rounds.each do |round| %>
				<% @score = find_users_score_for_round(round.id, @user.id) %>
				<div class="span1">
					<% if Score.exists?(@score) %>
						<%= render 'score_form' %>
					<% end %>
				</div>
			<% end %>
			<div class="span1"><%= calculate_total_score(@fight.id, fighter.id, @user.id) %></div>
	</div>
	<% end %>
</div>
<%= link_to "Clear Your Scorecard", destroy_all_scores_fight_path(@fight), data: { confirm: 'Are you sure?' }%>
<div class="container">
	<h4>CallTheFight.com Average Scorecard</h4>
	<%= render 'round_table' %>
	<% fighters.uniq.each do |fighter| %>
	<% @avg_total_scores = 0.00 %>
	<div class="row">
		<div class="span1"><%= fighter.name %></div>
			<% fighters_rounds = find_rounds_for_fights_fighter(@fight.id, fighter.id) %>
			<% fighters_rounds.each do |round| %>
				<% scores = find_all_users_scores_for_round(round.id) %>
				<% total_scores = 0 %>
				<% @eligible_scores = 0 %>
				<div class="span1">
					<% avg_total_scores = 0 %>
					<% scores.each do |score| %>
						<%# iterates through and adds up all the scores users submitted for this fighter's round as long as it's 6 or above%>
						<% if score.score >= 6 %>
							<% total_scores = total_scores + score.score %>
							<% @eligible_scores = @eligible_scores + 1 %>
						<% end %>
					<% end %>
					<% if @eligible_scores > 0.00 %>
						<% average_score = total_scores.to_f / @eligible_scores.to_f %>
						<%= number_with_precision(average_score, :precision => 2)%>
						<% @avg_total_scores = @avg_total_scores + average_score %>
					<% else %>
					--
					<% end %>
				</div>
			<% end %>
			<div class="span1"><%= number_with_precision(@avg_total_scores, :precision => 2) %></div>
	</div>
	<% end %>
</div>